### ISSUE TITLE
Compatibility Issue Django 2.2 psycopg>=2.9

### ISSUE THREAD

**Issue by wolbernd** [rdmorganiser/rdmo-docker-compose#12]
See also here: https://github.com/psycopg/psycopg2/issues/1293

Django 2.2 is incompatible with psycopg >= 2.9 due to some changes with regard to handling timezone infos. This leads to RDMO being unable to login users (Error 500 in Browser, no entry in logs) or importing catalogs (Stacktrace with `AssertionError: database connection isn't set to UTC`)

This can be fixed by installing psycopg-2.8.6 by changing the line `pip install psycopg2` in `rdmo/rootfs/opt/install-rdmo.sh` to `pip install psycopg2==2.8.6`.

**Comment by triole** [comment]
We know about this problem. RDMO version 1.6 will not use the psycopg library anymore because it upgrades to django3. The issue will disappear with the update. I will change the docker setup accordingly.

A discussion can be found here: rdmorganiser/rdmo#351
