### ISSUE TITLE
Refactoring Docker-Setup

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo-docker-compose#18]
Hi @triole,

this is an issue that aims at discussing potential setups in order to further ease the use of RDMO running inside docker. Although the current implementation using local images with the help of a `makefile` is working very well, I think it could be further improved towards implementing docker best practices.

As a user, I would like to have a single `docker-compose.yml` file that contains, all configuration of the docker setup. Furthermore, as in other projects it would be great if the images are centrally provided such as in the Docker Hub so that these need to be pulled only. This setup dramatically eases upgrades by pulling and starting up new images.

I see the advantage of building the images locally in order to easily create and use the current user ID to run processes inside the docker container, especially, because of the use of the docker volumes. But is it really needed to have the VE and the RDMO-App as a docker volume? Instead, the RDMO configuration file `local.py` as well as a rdmo theme might be integrated using docker volumes. This allows for central provision of the docker images.
For rewriting the user ID when starting the container, a similar approach than in the Jupyter Docker images might be used: https://github.com/jupyter/docker-stacks/blob/fbd5c88596df5139e16aa3b13fbb6dddc98c66be/base-notebook/start.sh#L84-L91 Or user namespaces might be used: https://docs.docker.com/engine/security/userns-remap/

Looking forward to your ideas on this setup.

Best regards
Max

**Comment by triole** [comment]
I started refactoring a few things because I feel that we could improve the setup.

This is the branch: https://github.com/rdmorganiser/rdmo-docker-compose/tree/refactor

The goal is to merge it into master at some point in the future.

**Comment by triole** [comment]
Closing this because branch is already merged to master.
