### ISSUE TITLE
Question about CI setup

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo-docker-compose#27]
Hi,
are the first two steps in the CI needed?
The Ubuntu image comes with docker and docker-compose pre-installed. Do you need a special version somehow?

**Comment by triole** [comment]
It might be new that ubuntu comes with docker-compose already installed. I remember a time where this was not the case. I suppose the workflow dates back to this. But of course, if it is installed now we don't need the first two steps. I'll have a look.

**Comment by triole** [comment]
I updated the workflow. Thanks for the hint.

**Comment by afuetterer** [comment]
You can delete this line
https://github.com/rdmorganiser/rdmo-docker-compose/blob/36bfb32957faa1f5ebe186b396747bbd6e7944bf/docker/rdmo/Dockerfile#L45

This command will install psycopg2
https://github.com/rdmorganiser/rdmo-docker-compose/blob/36bfb32957faa1f5ebe186b396747bbd6e7944bf/docker/rdmo/Dockerfile#L66

Actually you could also do this:
`python3 -m pip install rdmo[allauth,postgres]`
