### ISSUE TITLE
ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by AlexCosa-Linan** [rdmorganiser/rdmo-docker-compose#6]
I appreciate the issue "ImportError: cannot import name 'list_route' from rest_framework.decorators" has been solved 👍. However, I am not able to make it run yet. It seems that the module "django" does not exist in the virtual enviroment. 

> rdc-apache  | [Mon Jul 29 16:20:45.026356 2019] [wsgi:error] [pid 8:tid 140136115406592] [remote 127.0.0.1:47194] mod_wsgi (pid=8): Failed to exec Python script file '/vol/rdmo-app/config/wsgi.py'.
rdc-apache  | [Mon Jul 29 16:20:45.026391 2019] [wsgi:error] [pid 8:tid 140136115406592] [remote 127.0.0.1:47194] mod_wsgi (pid=8): Exception occurred processing WSGI script '/vol/rdmo-app/config/wsgi.py'.
rdc-apache  | [Mon Jul 29 16:20:45.026455 2019] [wsgi:error] [pid 8:tid 140136115406592] [remote 127.0.0.1:47194] Traceback (most recent call last):
rdc-apache  | [Mon Jul 29 16:20:45.026470 2019] [wsgi:error] [pid 8:tid 140136115406592] [remote 127.0.0.1:47194]   File "/vol/rdmo-app/config/wsgi.py", line 3, in <module>
rdc-apache  | [Mon Jul 29 16:20:45.026473 2019] [wsgi:error] [pid 8:tid 140136115406592] [remote 127.0.0.1:47194]     from django.core.wsgi import get_wsgi_application
rdc-apache  | [Mon Jul 29 16:20:45.026483 2019] [wsgi:error] [pid 8:tid 140136115406592] [remote 127.0.0.1:47194] ModuleNotFoundError: No module named 'django'

**Comment by AlexCosa-Linan** [comment]
Solved: The problem was in the vhost.conf. It works if 

> python-path=/vol/rdmo-app:/vol/ve/lib/python3.5/site-packages`

changes to

> python-path=/vol/rdmo-app:/vol/ve/lib/python3.7/site-packages

**Comment by jochenklar** [comment]
Hi, sorry I got confused between this repo and `rdmo-docker`. It would be better to use `home=/vol/rdmo-app python-home=/vol/ve` anyway. I will add this in the next days.

**Comment by jochenklar** [comment]
Ok, fixed in 55b1d79.
